# Generated by Django 3.1.5 on 2021-01-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20210118_2231'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default='01/01/0001', verbose_name='Date')),
                ('payment_method', models.CharField(default='', max_length=20, verbose_name='Payment method')),
                ('delivery_method', models.CharField(default='', max_length=50, verbose_name='Delivery method')),
                ('delivery_date', models.DateTimeField(default='', verbose_name='Delivery date')),
                ('total_price', models.FloatField(default='', max_length=20, verbose_name='Sub total')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default='01/01/0001', verbose_name='Date')),
                ('product_quantity', models.IntegerField(default='', max_length=20, verbose_name='Product Qty')),
                ('item_price', models.FloatField(default='', verbose_name='Item price')),
                ('sub_total', models.FloatField(default='', verbose_name='Sub total')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
    ]
