# Generated by Django 3.1.5 on 2021-01-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210119_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
