# Generated by Django 3.1.5 on 2021-01-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_productcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default='', max_length=30, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', max_length=80, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='', editable=False, max_length=25, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', editable=False, max_length=998, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='', editable=False, max_length=40, verbose_name='Product brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='year_of_manufacture',
            field=models.IntegerField(default=0, verbose_name='Year of manufacture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prise',
            field=models.FloatField(default=0, editable=False, verbose_name='Prise'),
        ),
    ]
