# Generated by Django 3.1.5 on 2021-01-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210118_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=25, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=998, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prise',
            field=models.FloatField(default=0, verbose_name='Prise'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='', max_length=40, verbose_name='Product brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=50, verbose_name='Product name'),
        ),
    ]
